# Generated by Django 3.2.5 on 2021-08-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
