# Generated by Django 3.2.5 on 2021-08-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0004_auto_20210830_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageobjects',
            options={'verbose_name_plural': 'Объекты страницы'},
        ),
        migrations.RemoveField(
            model_name='pageobjects',
            name='test_text',
        ),
    ]
