# Generated by Django 3.2.5 on 2021-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0005_auto_20210830_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageobjects',
            name='name_object',
            field=models.CharField(default=2, max_length=100, verbose_name='Название элемента'),
            preserve_default=False,
        ),
    ]
