# Generated by Django 3.2.5 on 2021-08-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0009_rename_title_pageobjects_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobjects',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Содержание'),
        ),
    ]
