# Generated by Django 3.2.5 on 2021-09-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0011_sectionobjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageobjects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionobjects',
            options={},
        ),
    ]
