# Generated by Django 3.2.5 on 2021-09-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0012_auto_20210901_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageobjects',
            options={'verbose_name_plural': 'Объекты страницы'},
        ),
        migrations.AlterModelOptions(
            name='sectionobjects',
            options={'verbose_name_plural': 'Элементы сектора'},
        ),
    ]
