# Generated by Django 3.2.5 on 2021-09-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0013_auto_20210901_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionobjects',
            name='sector',
        ),
    ]
