# Generated by Django 3.2.5 on 2021-09-01 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0014_remove_sectionobjects_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionobjects',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_calculator.pageobjects', verbose_name='Сектор'),
            preserve_default=False,
        ),
    ]
