# Generated by Django 3.2.5 on 2021-09-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0015_sectionobjects_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageobjects',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sectionobjects',
            options={},
        ),
        migrations.AlterField(
            model_name='pageobjects',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pageobjects',
            name='name_object',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionobjects',
            name='description_objects',
            field=models.JSONField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sectionobjects',
            name='range_objects',
            field=models.JSONField(max_length=100),
        ),
    ]
