# Generated by Django 3.2.5 on 2021-09-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0016_auto_20210901_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageobjects',
            options={'verbose_name_plural': 'Объекты страницы'},
        ),
        migrations.AlterModelOptions(
            name='sectionobjects',
            options={'verbose_name_plural': 'Элементы сектора'},
        ),
        migrations.AlterField(
            model_name='pageobjects',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='pageobjects',
            name='name_object',
            field=models.CharField(max_length=100, verbose_name='Название элемента'),
        ),
        migrations.AlterField(
            model_name='sectionobjects',
            name='description_objects',
            field=models.JSONField(max_length=100, verbose_name='Описание элементов '),
        ),
        migrations.AlterField(
            model_name='sectionobjects',
            name='range_objects',
            field=models.JSONField(max_length=100, verbose_name='Элементы диапазона'),
        ),
    ]
