# Generated by Django 3.2.5 on 2021-09-01 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0018_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionobjects',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_calculator.pageobjects'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='test',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='test_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_calculator.pageobjects'),
        ),
    ]
