# Generated by Django 3.2.5 on 2021-09-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0019_auto_20210901_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionobjects',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_calculator.pageobjects', verbose_name='Сектор'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='test_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='web_calculator.pageobjects'),
        ),
    ]
