# Generated by Django 3.2.5 on 2021-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0021_alter_sectionobjects_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionobjects',
            name='range_objects',
        ),
        migrations.AddField(
            model_name='sectionobjects',
            name='object_type',
            field=models.CharField(choices=[('1', 'Описание'), ('2', 'Диапазон'), ('3', 'Чекбокс')], default=2, max_length=1, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='sectionobjects',
            name='description_objects',
            field=models.JSONField(max_length=100, verbose_name='Элементы диапазона'),
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
