# Generated by Django 3.2.5 on 2021-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0023_auto_20210902_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobjects',
            name='content',
            field=models.JSONField(max_length=100, verbose_name='Содержание'),
        ),
    ]
