# Generated by Django 3.2.5 on 2021-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0025_pageobjects_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageobjects',
            name='data_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
