# Generated by Django 3.2.5 on 2021-09-06 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0026_pageobjects_data_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionobjects',
            name='data_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
