# Generated by Django 3.2.5 on 2021-09-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calculator', '0027_sectionobjects_data_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobjects',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
